# Site settings
title: John J. Camilleri
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnjcamilleri.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [Makefile, README.md]

# Other
ga_code: UA-11590274-1
